### ISSUE TITLE
MIssing update in CoreDNS-k8s_version.md

### ISSUE THREAD

**Issue by strus38** [coredns/deployment#247]
Hi
Could you please advise on the CoreDNS version for 1.20.x of K8S?
We see some master commits which may indicate 1.8.3 will be for 1.20.2, but 1.20.4 is out, so I was wondering if you could update the readme to find out if we need to stay on 1.7.0 or wait for 1.8.3.
Thanks!

**Comment by chrisohaver** [comment]
I updated the document. As for advise on which version to use...

If you want to leverage dualstack, then you'll need use CoreDNS 1.8.1. That version however introduced a bug that causes CoreDNS not to start if the K8s API is offline - I don't think it's a critical bug, but better to avoid it if dualstack is not needed. Hopefully the proposed fix will merge for 1.8.3.

Otherwise, 1.8.0 should be fine. 1.7.0 was installed with k8s 1.20 because 1.8.0 was released to near the end of the k8s 1.20 release cycle, and the kubernetes PR to bump it to 1.8.0 didn't get approved in time.  CoreDNS and K8s release schedules are not coordinated/synchronized.

**Comment by chrisohaver** [comment]
(I accidentally deleted this response while trying to edit it on my phone ...)

I've updated the document. As for advice on which version to use...

If you want to leverage dualstack, then you'll need use CoreDNS 1.8.1 or greater. That version however introduced a bug that causes CoreDNS not to start while the K8s API is offline - I don't think it's a critical bug, but better to avoid it if dualstack is not needed. Hopefully the proposed fix will merge for 1.8.4 (not released yet).

Otherwise, 1.8.0 should be fine. 1.7.0 was installed with k8s 1.20 because 1.8.0 was released to near the end of the k8s 1.20 release cycle, and the kubernetes PR to bump it to 1.8.0 didn't get approved in time. CoreDNS and K8s release schedules are not coordinated/synchronized.

**Comment by pawcykca** [comment]
Hi @chrisohaver,

Do you know if fix for below bug was merged and released in 1.8.4?
> If you want to leverage dualstack, then you'll need use CoreDNS 1.8.1 or greater. That version however introduced a bug that causes CoreDNS not to start while the K8s API is offline - I don't think it's a critical bug, but better to avoid it if dualstack is not needed. Hopefully the proposed fix will merge for 1.8.4 (not released yet).

Could you update this document for recent K8S versions (1.21 and 1.22)?

**Comment by chrisohaver** [comment]
> Do you know if fix for below bug was merged and released in 1.8.4?

Yeah, should be fixed in 1.8.4.

> Could you update this document for recent K8S versions (1.21 and 1.22)? 

Opened https://github.com/coredns/deployment/issues/254
